version: "2"

linters:
  default: none
  enable:
    - gocritic
    - goconst
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - errcheck
  exclusions:
    rules:
      # Suppress ST1005 - error strings capitalization  
      - linters: [staticcheck]
        text: "error strings should not be capitalized"
  settings:
    govet:
      enable:
        - shadow

formatters:
  enable:
    - goimports
