version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    ignore:
      # macOS doesn't support 32-bit architectures
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

release:
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"
